#
# Makefile for the touchscreen drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_TOUCHPANEL_GOODIX_GT9886) += GT9886/

obj-y += goodix_common.o
obj-y += goodix_tool.o
obj-y += gtx8_tools.o
obj-y += GT9897/


#endif
